### ISSUE TITLE
[Serverless]: Painless Lab Missing

### ISSUE THREAD

**Issue by davedenscombe** [elastic/docs-content#103]
### Serverless Docs

Dev tools

### Description

https://www.elastic.co/docs/current/serverless/devtools/debug-painless-scripts

Firstly, the navigation is wrong (it should be "Dev Tools" under Build, not "Development Tools").  Secondly, there appears to be no Painless Lab in Serverless so the doc page shouldn't even exist.

### Resources and additional context

.

**Comment by georgewallace** [comment]
Confirmed in Security and Observabilty that Painless lab does exist and is under Developer Tools and not Dev Tools in the UI. We do have badges on the docs page that does call out that it is in Obs and Security. Going to close this issue as the behavior in the docs is accurate. cc: @KOTungseth
