### ISSUE TITLE
[Serverless]: Project Settings -> Management - Navigation Instructions

### ISSUE THREAD

**Issue by davedenscombe** [elastic/docs-content#116]
### Serverless Docs

Project and management settings

### Description

https://www.elastic.co/docs/current/serverless/project-settings

The instructions instruct you to go to Project Settings, but you can't navigate to the parent page in the UI.  You would actually go to Project Settings -> Management.

Text: "Go to Project Settings to manage your indices, data views, saved objects, settings, and more."
Should be similar to "Go to Project Settings and click on Management to manage your indices, data views, saved objects, settings, and more.

![Image](https://github.com/user-attachments/assets/4cf4ff0d-dfa6-48bc-a5fe-f506999e3a8a)

### Resources and additional context

.

**Comment by georgewallace** [comment]
This has been resolved.
