### ISSUE TITLE
[Serverless]: Project Settings -> Management -> Machine Learning - Screenshot Wrong

### ISSUE THREAD

**Issue by davedenscombe** [elastic/docs-content#122]
### Serverless Docs

Project and management settings

### Description

https://www.elastic.co/docs/current/serverless/machine-learning

The first screenshot is wrong.

UI:
![Image](https://github.com/user-attachments/assets/117ac4c2-1034-4de0-946a-812d5714d522)

Documentation:
![Image](https://github.com/user-attachments/assets/fb4670f1-1a44-430d-910e-fb976c3245dc)

### Resources and additional context

.

**Comment by kosabogi** [comment]
Related PR: https://github.com/elastic/docs-content/pull/177
