### ISSUE TITLE
[Serverless]: Serverless Developer Tools -> Links result in error

### ISSUE THREAD

**Issue by maggieghamry** [elastic/docs-content#146]
### Serverless Docs

Welcome to Elastic Serverless

### Description

On the Serverless / Developer tools page, there are links under the `Available in` column, all which link to an empty page with an error:![Image](https://github.com/user-attachments/assets/4c0dc963-3918-4eb7-916d-c9724925759e)

Clicking on any of these links results in an error:
![Image](https://github.com/user-attachments/assets/eea7d584-f13a-4b4f-b287-79d296c58acd)

Additionally, clicking on the same icons in all subsequent `Dev tools` links results in the same errors
[Console](https://www.elastic.co/docs/current/serverless/devtools/run-api-requests-in-the-console)
[Search Profiler](https://www.elastic.co/docs/current/serverless/devtools/profile-queries-and-aggregations)
[Grok Debugger](https://www.elastic.co/docs/current/serverless/devtools/debug-grok-expressions)
[Painless Lab](https://www.elastic.co/docs/current/serverless/devtools/debug-painless-scripts)
[Troubleshooting](https://www.elastic.co/docs/current/serverless/devtools/dev-tools-troubleshooting)
![Image](https://github.com/user-attachments/assets/696d5772-f3ae-4592-83c7-87919e7a2186)

### Resources and additional context

Each of these links shows as active and hyperlinked, and should either be disabled or resolved to navigate to the corresponding information ![Image](https://github.com/user-attachments/assets/8ab42bff-78aa-4700-b36e-ff98f3b69f8b)
each of these icons leads to:
![Image](https://github.com/user-attachments/assets/d8caf5c9-e265-4345-bfc9-06d5b17d92b9)

**Comment by leemthompo** [comment]
I believe they're all missing the `current/` prefix in the URL

**Comment by maggieghamry** [comment]
Yes, it looks like it's removing `current/` in front of `serverless/`

**Comment by georgewallace** [comment]
after migration to asciidoc these badges now work as expected and no longer return a 404. cc: @leemthompo @KOTungseth
