### ISSUE TITLE
[Serverless]: Kibana Serverless API link not available under Kibana section

### ISSUE THREAD

**Issue by maggieghamry** [elastic/docs-content#147]
### Serverless Docs

Kibana Serverless API

### Description

Trying to find the `Kibana Serverless API` was very difficult; in fact I had to Google it to find the page at first. From the serverless main page:
![Image](https://github.com/user-attachments/assets/b60206a7-e005-4d3d-bafb-fad93865ace5)

![Image](https://github.com/user-attachments/assets/0da45321-6eed-40cb-a616-dcc3f7e35d8f)

The `Kibana Serverless APIs` is not clearly labeled, like the `Elasticsearch Serverless APIs` are. It would make more sense to change `Serverless management settings` to `Kibana Serverless` to coincide with all the others

![Image](https://github.com/user-attachments/assets/5c4df618-b171-46c1-ae10-7ef6a722ce2c)

### Resources and additional context

The Kibana Serverless API documentation is not named with the same structure as the other APIs, making it difficult to find through the internal documentation.

**Comment by georgewallace** [comment]
@lcawl Let's chat about this issue from the Serverless docs bash.

**Comment by lcawl** [comment]
The choice of URL and the title in the link are related to outstanding discussions about what "Kibana" is called in the serverless context. For now, however, I agree that it's simplest to just refer to it as "Kibana Serverless" in that API reference page so I've created https://github.com/elastic/tech-content/pull/496
