### ISSUE TITLE
[Serverless]: Connector API list contains mostly deprecated endpoint

### ISSUE THREAD

**Issue by michaelsupangkat** [elastic/docs-content#152]
### Serverless Docs

Kibana Serverless API

### Description

The Connector API documentation lists a couple of deprecated endpoints to interact with connectors. In fact the deprecated connector API are listed first instead of the non-deprecated ones. Would suggest to either remove deprecated endpoints from the doc, or if still in use, put them below and under a subheading - "Deprecated"

![Image](https://github.com/user-attachments/assets/558ab8f8-4521-47f0-a00c-f1847d4c3b6c)

### Resources and additional context

Context for this issue: https://www.elastic.co/docs/api/doc/serverless/operation/operation-2fapi-2factions-2faction-2f-7bid-7d-2f_execute-0

**Comment by lcawl** [comment]
These have been removed via https://github.com/elastic/kibana/pull/197510
