### ISSUE TITLE
[Serverless]: Kibana Base URL is indicated as localhost:5601 (No guide to retrieve actual serverless Kibana URL)

### ISSUE THREAD

**Issue by michaelsupangkat** [elastic/docs-content#153]
### Serverless Docs

Kibana Serverless API

### Description

In the entire API documentation (including the curl examples), Base URL still points to localhost, which could be confusing even as a placeholder. Should be replaced with a clearer placeholder value eg. <insert_kibana_url_here> and indicate where to retrieve the serverless Kibana URL

![Image](https://github.com/user-attachments/assets/c271bdea-e402-4ebf-b9a2-1febbaeeff60)

### Resources and additional context

Context of this issue is for https://www.elastic.co/docs/api/doc/serverless

**Comment by lcawl** [comment]
This PR will require investigation of where users can obtain the Kibana URL. Currently only the Elasticsearch API URL is covered in https://www.elastic.co/guide/en/serverless/current/elasticsearch-get-started.html#elasticsearch-get-started-copy-url

**Comment by lcawl** [comment]
I've created https://github.com/elastic/kibana/pull/202373 to differentiate the URLs used in the Kibana and Kibana Serverless OpenAPI documents.
