### ISSUE TITLE
[Serverless]: Elasticsearch Overview - Needed

### ISSUE THREAD

**Issue by georgewallace** [elastic/docs-content#157]
### Serverless Docs

Welcome to Elastic Serverless

### Description

Need to create an Elasticsearch Overview page similar to the other solutions.

### Resources and additional context

Align on consistency with the other solutions

**Comment by georgewallace** [comment]
@leemthompo Let's discuss this one, we can discuss as a team how we go forward with this.

**Comment by leemthompo** [comment]
Having a look at this one 👍

**Comment by leemthompo** [comment]
We determined that there isn't a need to have both a landing page and an overview page.

I've consolidated some improvements to the landing page in this PR: https://github.com/elastic/docs-content/pull/193
