### ISSUE TITLE
[Serverless]: Rename "Elasticsearch Serverless <type> plugin"

### ISSUE THREAD

**Issue by ppf2** [elastic/docs-content#158]
### Serverless Docs

Elasticsearch

### Description

https://www.elastic.co/docs/current/serverless/elasticsearch/ingest-data-through-logstash

>Logstash [Elasticsearch Serverless output plugin](https://www.elastic.co/guide/en/logstash/master/plugins-outputs-elasticsearch.html) 11.18.0 or later
Logstash [Elasticsearch Serverless input plugin](https://www.elastic.co/guide/en/logstash/master/plugins-inputs-elasticsearch.html) 4.18.0 or later
Logstash [Elasticsearch Serverless filter plugin](https://www.elastic.co/guide/en/logstash/master/plugins-filters-elasticsearch.html) 3.16.0 or later

We don't have Serverless specific Logstash plugins so the fact that we are calling the above "Elasticsearch Serverless .... plugin" can be misleading.

So I will suggest renaming the above to:

Logstash Elasticsearch output plugin 11.18.0 or later
Logstash Elasticsearch input plugin 4.18.0 or later
Logstash Elasticsearch filter plugin 3.16.0 or later

Thx!

### Resources and additional context

https://www.elastic.co/docs/current/serverless/elasticsearch/ingest-data-through-logstash

**Comment by georgewallace** [comment]
We are using variables for these strings, we should update these to not use the strings as they are incorrect for logstash as @ppf2 mentions. cc: @karenzone

**Comment by georgewallace** [comment]
These links are fixed after migrating the docs to asciidoc. Verified on the reported page that they do in fact state what it should be called. cc: @karenzone
