### ISSUE TITLE
[Serverless]: Project type icon links are broken

### ISSUE THREAD

**Issue by ppf2** [elastic/docs-content#169]
### Serverless Docs

Elasticsearch

### Description

![Image](https://github.com/user-attachments/assets/be803872-1f8d-46b4-a4a2-b4ad18f9f5a0)

If you click on any of the badge links, it goes to a 404 :)

![Image](https://github.com/user-attachments/assets/3a8c263d-eaf5-4517-b5c8-ef11a8e372b4)

For example, the Elasticsearch icon link goes to https://www.elastic.co/docs/serverless/elasticsearch/what-is-elasticsearch-serverless which does not exist.

### Resources and additional context

Example page: https://www.elastic.co/docs/current/serverless/elasticsearch/manage-project

We should verify that these badge icon links actually work anywhere though ...

**Comment by georgewallace** [comment]
after migration to asciidoc these badges now work as expected and no longer return a 404. cc: @leemthompo @KOTungseth
