### ISSUE TITLE
[Serverless]: Clarify the meaning of "time series" in docs

### ISSUE THREAD

**Issue by inqueue** [elastic/docs-content#216]
### Description

On https://www.elastic.co/guide/en/serverless/current/elasticsearch-manage-project.html, the wording in the Search AI Lake settings section is:
> 2. The volume of time series project data included in the Search Boost Window

And for search boost window:

> Non-time series data is always considered search-ready. The Search Boost Window determines the volume of time series project data that will be considered search-ready.
> 
> Increasing the window results in a bigger portion of time series project data included in the total search-ready data volume.

Missing is the definition of what "time series" actually means. In serverless, it is any document in standard indices or data streams having the `@timestamp` field. Having the definition is important since the presence of `@timestamp` determines if data will be subject to the boost window. In other words, data can be time series without `@timestamp` via another field in which case the data will not be subject to the boost window.

### Resources

The feature is already implemented in serverless.

### Which documentation set does this change impact?

Elastic Cloud (Hosted and Serverless) only

### Feature differences

The feature only impacts serverless.

### What release is this request related to?

N/A

### Collaboration model

The documentation team

### Point of contact.

**Main contact:** @

**Stakeholders:**

**Comment by leemthompo** [comment]
We should highlight this in the [Ingest your data](https://www.elastic.co/guide/en/serverless/current/elasticsearch-ingest-your-data.html) section too

**Comment by kosabogi** [comment]
Related PR: https://github.com/elastic/docs-content/pull/225
