### ISSUE TITLE
[Serverless]: Authentication realms will be supported at the platform level, not project level

### ISSUE THREAD

**Issue by ppf2** [elastic/docs-content#234]
### Serverless Docs

Elasticsearch

### Description

Elasticsearch Serverless documentation indicates that [authentication realms](https://www.elastic.co/guide/en/serverless/current/elasticsearch-differences.html#elasticsearch-differences-serverless-feature-planned) is a planned feature at the Elasticsearch project level but this is not the case.  

Security realms like SAML, OIDC is going to be supported (currently in preview) at the platform level (not at the project level) via the bring-your-own-IDP feature.

We should clarify this accordingly.

### Resources and additional context

https://www.elastic.co/guide/en/serverless/current/elasticsearch-differences.html#elasticsearch-differences-serverless-feature-planned

**Comment by alxchalkias** [comment]
Correction, BYOIdP currently only supports SAML, not OIDC.

**Comment by jakommo** [comment]
I wonder if the planed features section should just link to https://www.elastic.co/cloud/serverless/roadmap, rather than listing things in two places. Or is the roadmap more high level / less detailed?

**Comment by ppf2** [comment]
Also linking the separate doc request that recommends [linking to the roadmap page](https://github.com/elastic/docs-content/issues/224) from our various limitations and "Serverless differences" pages.  In general, how we represent limitations across project types and platform are quite [fragmented](https://github.com/elastic/docs-content/issues/78) today ...

**Comment by ppf2** [comment]
Resolved by https://github.com/elastic/docs-content/pull/248.   Thanks @bytebilly !
