### ISSUE TITLE
[REQUEST]: Add documentation on how to stop billing/charges for Serverless

### ISSUE THREAD

**Issue by jakommo** [elastic/docs-content#31]
### Description

For Serverless, we have documentation on how to manage billing and how to manage projects, but we do not have anything on how to stop billing/charges. 
What I'm requesting is something similar to [the Stop charges for a deployment](https://www.elastic.co/guide/en/cloud/current/ec-billing-stop.html) page that we have for Hosted deployments in Elasticsearch Service (ESS), but for Serverless.

### Resources

-

### Which documentation set does this change impact?

Elastic Cloud Serverless only

### Feature differences

-

### What release is this request related to?

N/A

### Collaboration model

Unknown

### Point of contact.

**Main contact:** @jakommo 

**Stakeholders:**

**Comment by mrjoechin** [comment]
Hello, can we please create a page and insert in the location shown below?

![](https://github.com/elastic/docs-content/assets/1121419/c304e35d-43db-4845-a96f-fdd7a36be26e)

Page Content

```
---
slug: /serverless/general/billing-stop-project
title: Stop charges for a project
description: How to stop charges for a project.
tags: [ 'serverless', 'general', 'billing' ]
---

<DocBadge template="technical preview" />
Got a project you no longer need and don’t want to be charged? Simply delete it.

Warning: All data is lost. Billing for usage is by the hour and any outstanding charges for usage before you deleted the project will still appear on your next bill.

To stop being charged for a project:
1. Log in to the [((ess-console-name))](((ess-console))).

2. Find your project on the home page in the Serverless Projects card and select Manage to access it directly. Or, select Serverless Projects to go to the projects page to view all of your projects.

3. Select Actions, then select Delete project and confirm the deletion.
```
