### ISSUE TITLE
[Serverless]: Typos and questions on serverless docs homepage

### ISSUE THREAD

**Issue by timto-elastic** [elastic/docs-content#62]
### Serverless Docs

Welcome to Elastic Serverless

### Description

https://www.elastic.co/docs/current/serverless
Typo: third bullet has a comma that should not be there after "threats" and probably needs a rewrite.
I'm assuming that this sentence will be removed: Elastic serverless products are currently in preview. [Learn more about serverless in our blog](https://www.elastic.co/blog/elastic-serverless-architecture).
I'm not sure if we are going to be linking to the blog by Ken still but it is a year old.
Do we need the Featured Topics? Is there a flow for initial setup. These are kind of general setup of subscription, users, etc. Do we drive to project flows first and then these other things as customers progress to real usage?

### Resources and additional context

See above

**Comment by georgewallace** [comment]
working with Evan Castle to get the link to the new blog for GA, expected to be live Nov 26. cc: @KOTungseth
