### ISSUE TITLE
[Serverless]: Management settings page typos and alignment issues of badges

### ISSUE THREAD

**Issue by formgeist** [elastic/docs-content#63]
Fixed in https://github.com/elastic/docs-content/pull/55

### Serverless Docs

Project and management settings

### Description

1. There's a small typo with the "Available in" column header
2. The badges for each solution don't really line up nice in the table, not sure if there's anything we can do about it though

### Resources and additional context

![Image](https://github.com/user-attachments/assets/199238aa-69a2-4c73-99b1-f41c0efaa133)

**Comment by florent-leborgne** [comment]
I'll fix the typo in another PR that I'm working on https://github.com/elastic/docs-content/pull/55

**Comment by florent-leborgne** [comment]
Text is fixed. I won't work on the badge alignment as I don't think this is super critical now.
