### ISSUE TITLE
[Serverless]: Assign user roles; update the user roles assignment screenshot

### ISSUE THREAD

**Issue by formgeist** [elastic/docs-content#64]
### Serverless Docs

Welcome to Elastic Serverless

### Description

I think we can provide a clearer and less visually messy screenshot than the one shown in the docs on this page for assigning roles.

https://www.elastic.co/docs/current/serverless/general/assign-user-roles

### Resources and additional context

![Image](https://github.com/user-attachments/assets/1e65cb98-f871-428f-ac9e-6337bc2a1788)

**Comment by georgewallace** [comment]
@KOTungseth do you have permissions to our test organization to grab this screenshot that is mentioned in the issue. I only have editor rights and can not see this view for serverless only cloud.

**Comment by KOTungseth** [comment]
@georgewallace I have access. What exactly do you want to show?

**Comment by georgewallace** [comment]
@KOTungseth just a cleaner screenshot. You don't have to add Jane Doe to the actual perms but if you can have the name there instead of the blacked out space and a cleaner screenshot that would be fantastic.

**Comment by KOTungseth** [comment]
How about this:

![Image](https://github.com/user-attachments/assets/fb504671-4796-46a5-a982-3b3e6fb3f527)

**Comment by KOTungseth** [comment]
Or this:

![Image](https://github.com/user-attachments/assets/c2d579f7-a747-4d0c-8f4e-df5d6efea20c)

**Comment by georgewallace** [comment]
Fantastic!
