### ISSUE TITLE
[Serverless]: Connector Run from source procedure clarifications

### ISSUE THREAD

**Issue by timto-elastic** [elastic/docs-content#68]
### Serverless Docs

Elasticsearch

### Description

Location: https://www.elastic.co/docs/current/serverless/elasticsearch/ingest-data-through-integrations-connector-client#run-from-source
The values should match the literals in the UI and in the config.yml file:
Current text: Replace the values for host (your Elasticsearch endpoint), api_key, connector_id, and service_type.
Should be: Replace the values for elasticsearch.host (your Elasticsearch endpoint), elasticsearch.api_key, connector_id, and service_type.

Should there be a link to the connectors report here or is clone command enough (I ask because the link to the example config.yml that is in the repo is linked...btw, I opened and copied it and then realized it was actually in the same repo...maybe say its actual name so I don't assume I'm getting it from somewhere else and I can easily find it in my cloned local directory)

Further up. The API key instructions are out of date.
Current text: elasticsearch.api_key: Your Elasticsearch API key. You can create API keys under Security → API keys. Once you connector is running, you'll be able to create a new API key that is limited to only access the connector's index.

What needs to be updated: Security → API keys should be Management → Access  → API keys

The elasticsearch.host value is also on the new connector page.
The editing of the config.yml is the same in both docker and python cases. The example was much more helpful in the docker section. We should probably reconcile them.

Also are there special permissions required because my API key on the service returns 401 from the elasticsearch host.

### Resources and additional context

![Image](https://github.com/user-attachments/assets/5dd60b23-97d1-4948-9d64-1f90fb87daca)

**Comment by leemthompo** [comment]
Thanks @timto-elastic! We'll investigate in our next sprint.

**Comment by leemthompo** [comment]
FYI the UI is set to change significantly before GA, so we need to keep an eye on [this issue](https://github.com/elastic/search-team/issues/8000) before attacking this one

**Comment by kosabogi** [comment]
Related PR: https://github.com/elastic/docs-content/pull/74
