### ISSUE TITLE
[Serverless]: Consolidate `Elastic serverless documentation` and `What is serverless Elastic?` pages

### ISSUE THREAD

**Issue by KOTungseth** [elastic/docs-content#69]
### Serverless Docs

Welcome to Elastic Serverless

## Move `Get started` to `Get started with serverless`
Since there is a dedicated [Get started with serverless](https://www.elastic.co/docs/current/serverless/general/sign-up-trial) page, move `Get started` cards to this page so all get started content lives on the same page.
![Image](https://github.com/user-attachments/assets/341d8a82-2f29-4d9f-acc3-f184da8f1f3a)

## Remove `Featured topics`
What is the problem we are trying to solve with the `Featured topics` cards?
![Image](https://github.com/user-attachments/assets/7052f619-6df2-4721-a137-cf43be226ebd)

Since the cards are duplicates of the topics in the left navigation, we can remove them. 

## Move `What is serverless Elastic?` content to `Elastic serverless documentation` 
The [What is serverless Elastic?](https://www.elastic.co/docs/current/serverless/general/what-is-serverless-elastic) content should be front and center instead of a subpage under `Elastic serverless documentation`. 

For customers evaluating serverless for their use case, we should provide them with the benefits of using serverless as soon as they land on the serverless docs. 

## Add `Control your data and performance` to list of serverless benefits
Change would look like:

- Management free. [Text]
- Autoscaled. [Text]
- Optimized data storage. [Text]
- Dedicated experiences. [Text]
- Pay per usage. [Text]
- **Data and performance control.** Control your project data and query performance against your project data. 
    - **Data.** Choose the data you want to ingest and the method to ingest it. By default, data is stored indefinitely in your project, 
          and you define the retention settings for your data streams. 
    - **Performance.** For granular control over costs and query performance against your project data, serverless projects come with 
          a set of predefined settings you can edit. 

We shouldn't be telling users that specific settings are not applicable to their project types. 
![Image](https://github.com/user-attachments/assets/dc2c4ff3-1543-4ce6-bb9d-99d5a56143ba)

This information should be included on only the [Manage your projects](https://www.elastic.co/docs/current/serverless/elasticsearch/manage-project) page, and `Control your data and performance` should be rewritten to apply to all projects. 

## Improve `Differences between serverless projects and hosted deployments on Elastic Cloud`
To focus on the benefits of using serverless over hosted deployments, rewrite the following:

`You can run [hosted deployments](https://www.elastic.co/guide/en/cloud/current/ec-getting-started.html) of the Elastic Stack on Elastic Cloud. These hosted deployments provide more provisioning and advanced configuration options.` 

### Resources and additional context

I should not have made this a required field

cc @colleenmcginnis

**Comment by georgewallace** [comment]
Related Issues: https://github.com/elastic/docs-content/issues/66 and https://github.com/elastic/docs-content/issues/62

**Comment by georgewallace** [comment]
related https://github.com/elastic/docs-content/issues/144
