### ISSUE TITLE
[Serverless]: Links redirections break in new browser tab / window.

### ISSUE THREAD

**Issue by renshuki** [elastic/docs-content#71]
### Serverless Docs

Welcome to Elastic Serverless

### Description

The links URLs in the left menu or the breadcrumb of the Elastic Serverless documentation are incorrect preventing new tab / window navigation.

### Resources and additional context

For example if you go to the [Get started with serverless](https://www.elastic.co/docs/current/serverless/general/sign-up-trial) page and look at the breadcrumbs URLs at the top:
![Image](https://github.com/user-attachments/assets/5eca004b-697b-4987-8f07-b177b2f4d398)

If you inspect the **Welcome to Elastic Serverless** page the links targets: `https://www.elastic.co/current/serverless` where it should be `https://www.elastic.co/docs/current/serverless` (where the `docs` part is missing).

(same issue for left menus)

There is a redirection from `https://www.elastic.co/current/serverless` to `https://www.elastic.co/docs/current/serverless` happening if you navigate normally using the breadcrumb or the left menu (SPA). However if you open one of the links to a new tab or window it ends up in a 404.

It's a UX issue preventing the navigation of the doc if you open new tabs / windows.

Tested on **Google Chrome - Version 129.0.6668.72 (Official Build) (arm64)**.

**Comment by georgewallace** [comment]
This has been corrected after moving to ASCIIdoc

**Comment by renshuki** [comment]
Thanks @georgewallace!
