### ISSUE TITLE
[Serverless]: https://www.elastic.co/docs/api/  dark mode turns the entire APIs Changelog > Latest changes dark including its text

### ISSUE THREAD

**Issue by ppf2** [elastic/docs-content#76]
### Serverless Docs

Elasticsearch Serverless API

### Description

This actually applies to https://www.elastic.co/docs/api/ which is not part of the bug bash, but it's a link that is "on the way" to the sections to be reviewed for bug bash :)

When switched to dark mode for APIs Changlog, the entire latest changes history turned dark, masking the actual text that should show up:

![Image](https://github.com/user-attachments/assets/2969a6a6-581e-4bc0-b53e-928b62c0c525)

The workaround is to mouseover and drag over the text to select them for viewing:

![Image](https://github.com/user-attachments/assets/593d9e1b-34d2-45fc-adc9-435a50da968a)

### Resources and additional context

https://www.elastic.co/docs/api/

**Comment by KOTungseth** [comment]
Updated to a lighter brand color

![Image](https://github.com/user-attachments/assets/d95f88c8-c86b-42a0-bb41-1663a1350e0c)
