### ISSUE TITLE
[Serverless]: Clarify Serverless and Stateful clients compatibility with Serverless and non-Serverless environments

### ISSUE THREAD

**Issue by ppf2** [elastic/docs-content#80]
### Serverless Docs

Elasticsearch

### Description

Let's clarify Serverless clients vs. non-Serverless clients: https://www.elastic.co/docs/current/serverless/elasticsearch/clients

We have seen confusion by multiple customers while reviewing Serverless cases where they are attempting to use Serverless clients against non-Serverless deployments and vice versa.

In short, our current stance is:
- Serverless client will _only work on Serverless_
- Non-Serverless (Stateful) clients may work on Serverless but there will be a lag in the release to support Serverless features.  Also some feature gap like autocomplete are not supported when used with Serverless.  @technige can provide additional details.

It will be helpful to put up banners for each language client's documentation page on both Serverless and Stateful clients documentation so that regardless of whether the customer lands in Serverless clients documentation or Stateful clients documentation, they will see a disclaimer about these clients' compatibility with Serverless and non-Serverless environments.

### Resources and additional context

https://www.elastic.co/docs/current/serverless/elasticsearch/clients 
https://www.elastic.co/guide/en/elasticsearch/client/index.html

**Comment by marciw** [comment]
- [ ] Part 1, in progress: add banners to serverless client docs
- [ ] Part 2, not required for serverless GA: elastic/search-docs-team#225

**Comment by marciw** [comment]
I temporarily reopened this because I thought I needed to track the [Part 2 work](https://github.com/elastic/docs-content/issues/80#issuecomment-2477582923) in this issue, but we'll do that in the other issue. Closing again.
