### ISSUE TITLE
[Serverless]: Update wording on the Elasticsearch Get Started page

### ISSUE THREAD

**Issue by tatianafinamor** [elastic/docs-content#86]
### Serverless Docs

Elasticsearch

### Description

Update the wording to be more clear where to locate the Elasticsearch endpoint 
![Image](https://github.com/user-attachments/assets/84d5af87-56b2-48e9-8c2e-ee72bc7f6836)

suggestion:

1. At the top of the Overview page, click on "View" next to "Connection details."

2. Under the "Connection details" section, find the "Elasticsearch Endpoint" field.

3. Copy the URL for the Elasticsearch Endpoint, as you will use this URL to send all Elasticsearch API requests.

Store this value along with your encoded API key. You'll use both values in the next step.

### Resources and additional context

Working on the serverless docs bug bash.

**Comment by kosabogi** [comment]
Related PR: https://github.com/elastic/docs-content/pull/181
