### ISSUE TITLE
[Serverless]: Update naming across the board

### ISSUE THREAD

**Issue by georgewallace** [elastic/docs-content#93]
### Serverless Docs

Welcome to Elastic Serverless

### Description

The official naming for serverless in general as well as the projects are listed below. We need to review our content to ensure we are using the right naming. 

Serverless - Elastic Cloud Serverless
Elasticsearch - Elasticsearch Serverless 
Observability - Elastic Observability Serverless
Security - Elastic Security Serverless

### Resources and additional context

An example of something that needs to be updated can be seen below:

![Image](https://github.com/user-attachments/assets/c1727cfd-b43f-47f3-ba0e-386640334d20)

**Comment by georgewallace** [comment]
variables to use:
@leemthompo can you confirm this is right based on the updates you are making?

|Naming|When to use | variable|
|---|---|---|
|Elastic Cloud Serverless|when talking about serverless all up|{serverless-full}|
|Elasticsearch Serverless|when talking about the Elasticsearch project in serverless|{es-serverless}|
|Elasticsearch|when talking about Elasticsearch as a product |{es}|

**Comment by leemthompo** [comment]
I confirm 👍

**Comment by leemthompo** [comment]
For those following along at home, this was the PR of interest: https://github.com/elastic/docs-content/pull/196
