### ISSUE TITLE
[Serverless]: Aggregations

### ISSUE THREAD

**Issue by georgewallace** [elastic/docs-content#94]
### Serverless Docs

Welcome to Elastic Serverless

### Description

On the [Aggregations](https://www.elastic.co/docs/current/serverless/elasticsearch/explore-your-data-aggregations) page:

1. "Note that [scripted metric aggregations](https://www.elastic.co/guide/en/elasticsearch/reference/master/search-aggregations-metrics-scripted-metric-aggregation.html) are not available in serverless Elasticsearch." should be an actual note and not just in-line text. Could also be under the list as a footnote.
2. Review the list under "Elasticsearch organizes aggregations into three categories:". Is this list consistent with the other lists across all of our pages?
3. Under "Aggregation results are in the response's aggregations object:" the example should use []s in hits, this is a property that will return a sub array, while it isn't critical, it lets folks understand that their output in that section could be longer. I.e if it found 17 hits, there would be 17 objects under hits. Technically it is under hits.hits.
4. Considering the user most likely came from [Get Started](https://www.elastic.co/docs/current/serverless/elasticsearch/get-started) we should re-think the aggregation examples as the one with time spans uses 1day, and the example on the Get Started page, uses timestamps from over 15 years ago. 
5. In the sentence "The response returns the aggregation type as a prefix to the aggregation's name." we talk about the aggregation types, should we provide a link to the types here?
6. Under "Aggregation caches" we discuss how things are cached. The links take you to the `request_cache` docs, when you try to run any of the examples on the stateful docs for it you get an error `Request for uri [/books/_stats/request_cache?human] with method [GET] exists but is not available when running in serverless mode`

### Resources and additional context

This feedback is in regards to [Aggregations](https://www.elastic.co/docs/current/serverless/elasticsearch/explore-your-data-aggregations)

**Comment by leemthompo** [comment]
This content duplicates https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations.html

Even independent of docs re-migration, I'd advocate for removing duplicate tutorials here and just linking to the original.

Let's see where we get to with our discussions about that re-migration plan.

**Comment by leemthompo** [comment]
Hey @georgewallace because I've got this aggregations quick start in the pipeline, might be worth you having a run through see what you think?

https://github.com/elastic/elasticsearch/pull/116251

**Comment by georgewallace** [comment]
Agreed. Let's discuss the search and explore your data sections. If we already have the content for each of these we can keep the heading pages and maybe beef them up a bit and point to the source of truth.

**Comment by georgewallace** [comment]
Closing this issue as @leemthompo deeduped the Explore your data section in https://github.com/elastic/docs-content/pull/202
