### ISSUE TITLE
[Serverless]: Update Elasticsearch Manage alerting rules page

### ISSUE THREAD

**Issue by tatianafinamor** [elastic/docs-content#96]
### Serverless Docs

Welcome to Elastic Serverless

### Description

Update the steps to create a new Alert to:

In **Alerts and Insights** or **Project settings** → **Management** → **Alerts and Insights** → **Rules** you can:

Create and edit rules
Manage rules including enabling/disabling, muting/unmuting, and deleting
Drill down to rule details
Configure rule settings

### Resources and additional context

Update the content to look like this:

![Image](https://github.com/user-attachments/assets/5ce38a16-9cf0-4b6c-bc49-c49d6887f132)

**Comment by kosabogi** [comment]
Based on my discussion with @tatianafinamor, this issue suggests updating the [Kibana guide > Create and manage rules](https://www.elastic.co/guide/en/kibana/master/create-and-manage-rules.html) page, not the Serverless guide. Users need clearer guidance on how to navigate to the **Rules** section.

Related PR: 

https://github.com/elastic/kibana/pull/202648

**Comment by tatianafinamor** [comment]
Adding correct image suggestion to update the page ![Image](https://github.com/user-attachments/assets/61e2d701-1b9b-4a0b-b2bc-0d039436afa5)
