### ISSUE TITLE
[Serverless]: Project Settings -> Management -> Connectors needs more context in the description

### ISSUE THREAD

**Issue by timto-elastic** [elastic/docs-content#98]
### Serverless Docs

Project and management settings

### Description

On this page, add more context so it can be more easily disambiguated from kibana ingest connectors: https://www.elastic.co/docs/current/serverless/action-connectors.

Should we also be disambiguating in the titles as well...or have abstracts in search results? See the search image below.

![Image](https://github.com/user-attachments/assets/4581b30f-5164-4be1-8f2b-4ac1c18b4213)
![Image](https://github.com/user-attachments/assets/9b8b1f85-35a6-492d-8614-84c5ef4d889e)

### Resources and additional context

https://www.elastic.co/docs/current/serverless/action-connectors

**Comment by timto-elastic** [comment]
@jmikell821 @leemthompo should we have an item in the glossary clarifying all the different connectors?

**Comment by georgewallace** [comment]
Doublecheck that the list is complete
