### ISSUE TITLE
[Serverless]: Grok Debugger - Navigation Instructions are Wrong

### ISSUE THREAD

**Issue by davedenscombe** [elastic/docs-content#99]
### Serverless Docs

Dev tools

### Description

This page: https://www.elastic.co/docs/current/serverless/devtools/debug-grok-expressions

Under Get Started the following is stated:
From the main menu, click Developer Tools, then click Grok Debugger.

This is wrong, the correct navigation should be to go to Dev Tools under Build, then click Grok Debugger.

### Resources and additional context

.

**Comment by kosabogi** [comment]
Related PR: https://github.com/elastic/docs-content/pull/206
